### PR TITLE
Be able to use this in a typescript project with webpack

### PR DESCRIPTION
**Pull request by davidnbooth**
This library is really nice!  Thanks :)

I added a type declaration file and a UMD pattern for exports, so that I can use this in a typescript project using webpack to bundle the code.

I also ran the [cspell](https://www.npmjs.com/package/cspell) spell checker.

### CODE REVIEW

**Review by hugolpz — APPROVED** [review]

**Comment by hugolpz** [comment]
@davidnbooth , thank for this fast jump into our project's code. I'm coordinator and not qualified enough to review this PR, I will try my best to organize a speedy review.
- There are a lot of changes. Did you test them thoroughly ? If you are using this library in a live project that's better.
- I will contact the relevant person to ask for a code review.

**Comment by davidnbooth** [comment]
@hugolpz thanks for the quick response!  I'll go through the commits:

- "Run spell checker" **_this is actually a breaking change because the event name changed from "stoped" to "stopped"_**.  Maybe I should roll that back.
- "htmlhint" I think this is fine and it only affects the demo so it should be okay
- "Create a type declaration file/Make type declarations better" this doesn't actually affect any of the code, its just so that someone using this in a typescript project can copy it in (or we could try to submit it to DefinitelyTyped), so it shouldn't break anything.  It worked well for me in the typescript project I am working on.
- "add UMD pattern for different import styles" I'm not an expert on this but I did try to use the library in the normal way, with script tags, and it all worked the same as it had before I added this.  The benefit was that this also let me use ES6 imports and webpack to import the library into my typescript project.  **_I did add some code so that it adds a .LinguaRecorder property to the global object, which could theoretically break people's code if they were adding their own global window.LinguaRecorder, but I don't think that is likely_**

The only two changes that I think are possibly problematic are the ones I highlighted above.

Thanks again :)

**Comment by 0x010C** [comment]
Hi @davidnbooth, sorry for the delay, I had a busy month.

I know very litle about typescript, so I'll put trust in you on that part. I run many tests and everything seems to be running fine.

The only major change I see is the switch from "stoped" to "stopped". In fact it is a good point but it will break some existing code-base. Rolling-back isn't a solution either, as this spelling error can cause confusion for people who use this library, and must therefore be corrected. That's why I introduced an alias with a depreciation warning, which will be removed during a major update in the future.

I'll do the merge and publish the new version in the evening.

Many thanks for your PR and your comments!

**Review by 0x010C — APPROVED** [review]

**Comment by hugolpz** [comment]
Wonderful. Thank you both. Thank you @0x010C.

@davidnbooth , if you use the lib online feel free to show us where, we celebrate whenever our project is helpful to others. For profits or competition included. 🎉

For next Lingualibre.org update, a light reminder:
- stoped --> stopped
- rtrim --> rTrim
- ltrim --> lTrim
Maybe some others.

**Pull request merged**
